### ISSUE TITLE
[Bug/README unclear] KeyError: 'plugin_type' Container nomad_oasis_app: unhealthy

### ISSUE THREAD

**Issue by ChristinaMariaMayrBirg** [FAIRmat-NFDI/nomad-distro-template#22]
# Bug

When I follow the instructions from the README, I get the following error:

![Screenshot from 2024-09-10 17-04-02](https://github.com/user-attachments/assets/0a6534b0-a6e8-4ff0-bd54-7d3dcf12ac91)

I checked the container log of the container nomad_oasis_app. It says:  `KeyError: 'plugin_type'`

```
[2024-09-10 15:01:07 +0000] [45] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 75, in init_process
    super().init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/site-packages/nomad/app/main.py", line 30, in <module>
    from nomad import infrastructure
  File "/usr/local/lib/python3.11/site-packages/nomad/infrastructure.py", line 49, in <module>
    from nomad.parsing import parsers  # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nomad/parsing/__init__.py", line 19, in <module>
    from nomad.parsing.parser import (
  File "/usr/local/lib/python3.11/site-packages/nomad/parsing/parser.py", line 34, in <module>
    from nomad.datamodel import EntryArchive, EntryMetadata
  File "/usr/local/lib/python3.11/site-packages/nomad/datamodel/__init__.py", line 23, in <module>
    from .datamodel import (
  File "/usr/local/lib/python3.11/site-packages/nomad/datamodel/datamodel.py", line 29, in <module>
    from nomad.datamodel.metainfo.common import FastAccess
  File "/usr/local/lib/python3.11/site-packages/nomad/datamodel/metainfo/__init__.py", line 52, in <module>
    config.load_plugins()
  File "/usr/local/lib/python3.11/site-packages/nomad/config/models/config.py", line 1155, in load_plugins
    }.get(plugin_config['plugin_type'])
          ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'plugin_type'
```

Please find the full container log of the container nomad_oasis_app here:

[logs_nomad_oasis_app.txt](https://github.com/user-attachments/files/16947041/logs_nomad_oasis_app.txt)

**Comment by NiclRich** [comment]
This is the same error as in the Issue here: https://github.com/FAIRmat-NFDI/nomad-distribution-template/issues/21

**Comment by blueraft** [comment]
Could you share the Dockerfile contents and the default_plugins.txt contents? I can try to reproduce it then
